force-app/main/default/objects/TerritoryAllocator__c/TerritoryAllocator__c.object-meta.xml
<CustomObject>
    <label>TerritoryAllocator</label>
    <nameField>
        <label>TerritoryAllocator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TerritoryAllocators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryAllocator__c/fields/Account_field__c.field-meta.xml
<CustomField>
    <fullName>Account_field__c</fullName>
    <description>Accout filed  to compare  with</description>
    <label>Account field</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Advanced_logic__c.field-meta.xml
<CustomField>
    <fullName>Advanced_logic__c</fullName>
    <description>used to add a  combination of AND/OR statements for Rule item record type records</description>
    <label>Advanced logic</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Built_SOQL__c.field-meta.xml
<CustomField>
    <fullName>Built_SOQL__c</fullName>
    <description>Build here the final SOQL  statement for this level</description>
    <label>Built_SOQL</label>
    <length>4500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Comparison_Value__c.field-meta.xml
<CustomField>
    <fullName>Comparison_Value__c</fullName>
    <label>Comparison Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Geo__c.field-meta.xml
<CustomField>
    <fullName>Geo__c</fullName>
    <label>Geo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>NORAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/isBottom__c.field-meta.xml
<CustomField>
    <fullName>isBottom__c</fullName>
    <defaultValue>false</defaultValue>
    <description>specify  if this  record corresponds to the bottom territory branch</description>
    <label>isBottom</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Local_filter__c.field-meta.xml
<CustomField>
    <fullName>Local_filter__c</fullName>
    <description>OQL  stattement resulted from record  Condition</description>
    <label>Local filter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Local_SOQL__c.field-meta.xml
<CustomField>
    <fullName>Local_SOQL__c</fullName>
    <description>SOQL build based on Local criteria or from HUB Item local SOQLs</description>
    <label>Local SOQL</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EQUAL</fullName>
            </value>
            <value>
                <fullName>NOT_EQUAL</fullName>
            </value>
            <value>
                <fullName>GREATER</fullName>
            </value>
            <value>
                <fullName>LESS</fullName>
            </value>
            <value>
                <fullName>STARTS_WITH</fullName>
            </value>
            <value>
                <fullName>END_WITH</fullName>
            </value>
            <value>
                <fullName>CONTAINS</fullName>
            </value>
            <value>
                <fullName>BETWEEN</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>NOT_IN</fullName>
            </value>
            <value>
                <fullName>IN_SPLITTEDITEM</fullName>
            </value>
            <value>
                <fullName>ISNULL</fullName>
            </value>
            <value>
                <fullName>NOT_BETWEEN</fullName>
            </value>
            <value>
                <fullName>NOT_CONTAINS</fullName>
            </value>
            <value>
                <fullName>NOTNULL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Order_of_Execution__c.field-meta.xml
<CustomField>
    <fullName>Order_of_Execution__c</fullName>
    <description>when runnign batches for Territory this is the order of the territory specific batch in th chain</description>
    <label>Order of Execution</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/ParentAllocator__c.field-meta.xml
<CustomField>
    <fullName>ParentAllocator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ParentAllocator</label>
    <referenceTo>TerritoryAllocator__c</referenceTo>
    <relationshipLabel>TerritoryAllocators</relationshipLabel>
    <relationshipName>TerritoryAllocators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Segment__c.field-meta.xml
<CustomField>
    <fullName>Segment__c</fullName>
    <label>Segment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CORP</fullName>
            </value>
            <value>
                <fullName>ENT</fullName>
            </value>
            <value>
                <fullName>HIED</fullName>
            </value>
            <value>
                <fullName>K12</fullName>
            </value>
            <value>
                <fullName>MM</fullName>
            </value>
            <value>
                <fullName>RTO</fullName>
            </value>
            <value>
                <fullName>IS</fullName>
            </value>
            <value>
                <fullName>CORP_ENT</fullName>
            </value>
            <value>
                <fullName>CORP_MM</fullName>
            </value>
            <value>
                <fullName>CORP_IS</fullName>
            </value>
            <value>
                <fullName>SMB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Territory_Market__c.field-meta.xml
<CustomField>
    <fullName>Territory_Market__c</fullName>
    <label>Territory Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EDU</fullName>
            </value>
            <value>
                <fullName>CORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/TerritoryTeam__c.field-meta.xml
<CustomField>
    <fullName>TerritoryTeam__c</fullName>
    <label>TerritoryTeam</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NORAM HIED East</fullName>
            </value>
            <value>
                <fullName>NORAM HIED West</fullName>
            </value>
            <value>
                <fullName>NORAM HIED Central</fullName>
            </value>
            <value>
                <fullName>NORAM K12 East</fullName>
            </value>
            <value>
                <fullName>NORAM K12 Central</fullName>
            </value>
            <value>
                <fullName>NORAM CORP ENT</fullName>
            </value>
            <value>
                <fullName>NORAM CORP MM 1</fullName>
            </value>
            <value>
                <fullName>NORAM CORP MM 2</fullName>
            </value>
            <value>
                <fullName>NORAM CORP SME 1</fullName>
            </value>
            <value>
                <fullName>LATAM HIED Spanish</fullName>
            </value>
            <value>
                <fullName>LATAM HIED Brazil</fullName>
            </value>
            <value>
                <fullName>HIED AUSNZ</fullName>
            </value>
            <value>
                <fullName>HIED ASIA</fullName>
            </value>
            <value>
                <fullName>K12 AUSNZ</fullName>
            </value>
            <value>
                <fullName>RTO AUSNZ</fullName>
            </value>
            <value>
                <fullName>APAC CORP</fullName>
            </value>
            <value>
                <fullName>EMEA EDU ENT</fullName>
            </value>
            <value>
                <fullName>EMEA EDU MM UK</fullName>
            </value>
            <value>
                <fullName>EMEA EDU MM BENONORD</fullName>
            </value>
            <value>
                <fullName>EMEA EDU MM EMERG</fullName>
            </value>
            <value>
                <fullName>EMEA EDU INSIDE</fullName>
            </value>
            <value>
                <fullName>EMEA CORP ENT 1</fullName>
            </value>
            <value>
                <fullName>EMEA CORP MM</fullName>
            </value>
            <value>
                <fullName>EMEA CORP IS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GEO</fullName>
            </value>
            <value>
                <fullName>SEGMENT</fullName>
            </value>
            <value>
                <fullName>CUSTOM</fullName>
            </value>
            <value>
                <fullName>LOCATION</fullName>
            </value>
            <value>
                <fullName>CUSTOM_SPLITTED</fullName>
            </value>
            <value>
                <fullName>CUSTOM_SPLIT_ITEM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Validate__c.field-meta.xml
<CustomField>
    <fullName>Validate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if  checked  on update we validate the Query then we clear this flag.</description>
    <label>Validate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/recordTypes/HUB_BRANCH.recordType-meta.xml
<RecordType>
    <fullName>HUB_BRANCH</fullName>
    <active>true</active>
    <description>Allocatort record  with Where clause built from HUB ITEM records. Can have both Hub Items and  Nodes as children</description>
    <label>HUB</label>
</RecordType>

force-app/main/default/objects/TerritoryAllocator__c/recordTypes/HUB_ITEM.recordType-meta.xml
<RecordType>
    <fullName>HUB_ITEM</fullName>
    <active>true</active>
    <description>Item of a HUB record. No more braches down. Its local filter are assembled at HUB level. Can have only HUB as parent</description>
    <label>HUB_ITEM</label>
</RecordType>

force-app/main/default/objects/TerritoryAllocator__c/recordTypes/NODE.recordType-meta.xml
<RecordType>
    <fullName>NODE</fullName>
    <active>true</active>
    <description>Allocator record which define its own Local query Can have HUB or NODE as children. No HUB Item</description>
    <label>NODE</label>
</RecordType>

force-app/main/default/objects/TerritoryAllocatorItem__c/TerritoryAllocatorItem__c.object-meta.xml
<CustomObject>
    <label>Territory Allocator Item</label>
    <nameField>
        <displayFormat>TA_ITEM-{0000}</displayFormat>
        <label>TerrtoryAllocatorItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TerritoryAllocatorItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryAllocatorItem__c/fields/Allocator__c.field-meta.xml
<CustomField>
    <fullName>Allocator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Allocator</label>
    <referenceTo>TerritoryAllocator__c</referenceTo>
    <relationshipLabel>TerritoryAllocatorItems</relationshipLabel>
    <relationshipName>TerrtoryAllocatorItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocatorItem__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>Account field</description>
    <label>Field</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocatorItem__c/fields/Item_Value__c.field-meta.xml
<CustomField>
    <fullName>Item_Value__c</fullName>
    <label>Item Value</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TerritoryBuilderHelper_test.cls
@isTest
public class TerritoryBuilderHelper_test {
  @testSetup
  static void testSetup() {
    TestFactory.createSObject(
      new TerritoryAllocator__c(
        Geo__c = 'NORAM',
        Account_field__c = 'TerritoryGeo__c',
        Operator__c = 'EQUAL'
      ),
      true
    );
  }

  @isTest
  static void testCreateSplitAllocator() {
    ID allocRT = Schema.SObjectType.TerritoryAllocator__c.getRecordTypeInfosByDeveloperName()
      .get('NODE')
      .getRecordTypeId();
    TerritoryAllocator__c theSplittedNode = new TerritoryAllocator__c(
      Geo__c = 'NORAM',
      Account_field__c = 'ShippingPostalCode4Terr__c',
      Operator__c = 'IN_SPLITTEDITEM',
      Type__c = 'CUSTOM_SPLITTED'
    );
    theSplittedNode.RecordtypeId = allocRT;
    theSplittedNode = (TerritoryAllocator__c) TestFactory.createSObject(
      theSplittedNode,
      true
    );

    TerritoryAllocatorItem__c theSplittedItem1 = new TerritoryAllocatorItem__c();
    theSplittedItem1.Active__c = true;
    theSplittedItem1.Allocator__c = theSplittedNode.id;
    theSplittedItem1.Field__c = 'ShippingPostalCode4Terr__c';
    theSplittedItem1.Item_Value__c = 'item1';
    theSplittedItem1 = (TerritoryAllocatorItem__c) TestFactory.createSObject(
      theSplittedItem1,
      true
    );

    TerritoryAllocatorItem__c theSplittedItem2 = new TerritoryAllocatorItem__c();
    theSplittedItem2.Active__c = true;
    theSplittedItem2.Allocator__c = theSplittedNode.id;
    theSplittedItem2.Field__c = 'ShippingPostalCode4Terr__c';
    theSplittedItem2.Item_Value__c = 'item2';
    theSplittedItem2 = (TerritoryAllocatorItem__c) TestFactory.createSObject(
      theSplittedItem2,
      true
    );

    TerritoryBuilderHelper.CreateSplitAllocator(theSplittedNode);
    String expected = 'ShippingPostalCode4Terr__c IN ( \'item1\',\'item2\' )';
    String actual = theSplittedNode.Built_SOQL__c;
    System.AssertEquals(expected, actual, 'Expect Allocator BuildSQL to match');
  }

  /****************************************

****************************************/
  @isTest
  static void testBuildHUBquery() {
    TerritoryAllocator__c theHUB = new TerritoryAllocator__c(
      Geo__c = 'NORAM',
      Account_field__c = 'TerritoryGeo__c',
      Advanced_logic__c = '(HI1 AND HI2)'
    );
    ID allocRT = Schema.SObjectType.TerritoryAllocator__c.getRecordTypeInfosByDeveloperName()
      .get('HUB_BRANCH')
      .getRecordTypeId();
    theHUB.RecordtypeId = allocRT; //'012S0000000ZyRi';  //DO NOT HARDCODE
    theHUB = (TerritoryAllocator__c) TestFactory.createSObject(theHUB, true);

    List<TerritoryBuilderHelper.SQLBuilderWrapper> params = new List<TerritoryBuilderHelper.SQLBuilderWrapper>();
    TerritoryBuilderHelper.SQLBuilderWrapper bw = new TerritoryBuilderHelper.SQLBuilderWrapper();

    bw.currentRecord = theHUB;
    params.add(bw);

    allocRT = Schema.SObjectType.TerritoryAllocator__c.getRecordTypeInfosByDeveloperName()
      .get('HUB_ITEM')
      .getRecordTypeId();
    TerritoryAllocator__c theTA1 = new TerritoryAllocator__c(
      Name = 'HI1',
      Geo__c = 'NORAM',
      Account_field__c = 'TerritoryGeo__c',
      Operator__c = 'EQUAL',
      Comparison_Value__c = 'NORAM',
      ParentAllocator__c = theHUB.id,
      Local_filter__c = 'TerritoryGeo__c = \'NORAM\''
    );
    theTA1.RecordtypeId = allocRT;
    theTA1 = (TerritoryAllocator__c) TestFactory.createSObject(theTA1, true);
    TerritoryAllocator__c theTA2 = new TerritoryAllocator__c(
      Name = 'HI2',
      Geo__c = 'NORAM',
      Account_field__c = 'Institution_FTE__c',
      Operator__c = 'LESS',
      Comparison_Value__c = '100',
      ParentAllocator__c = theHUB.id,
      Local_filter__c = 'Institution_FTE__c < 100'
    );
    theTA2.RecordtypeId = allocRT; //'012S0000000ZyW0'; //DO NOT HARDCODE
    theTA2 = (TerritoryAllocator__c) TestFactory.createSObject(theTA2, true);

    String expected = '(TerritoryGeo__c = \'NORAM\' AND Institution_FTE__c < 100)';
    List<String> retval = TerritoryBuilderHelper.buildHUBquery(params);
    System.assertEquals(1, retval.size(), 'Expect to have 1 Build SQL item');
    System.AssertEquals(
      expected,
      retval[0],
      'Expect Allocator BuildSQL to match'
    );
  }

  /**************************************
   String ValidateSOQL(String Whereclause)
**************************************/
  @isTest
  static void testValidateSOQL() {
    String thewhere = 'Name = \'noname\' ';
    String retval = TerritoryBuilderHelper.ValidateSOQL(theWhere);
    System.AssertEquals(
      retval.startswith('VALID'),
      true,
      'Expect Build SQL to be a valid SOQL'
    );

    thewhere = 'Namu = \'noname\' ';
    retval = TerritoryBuilderHelper.ValidateSOQL(theWhere);
    System.AssertEquals(
      retval.startswith('No such column '),
      true,
      'the return ed SOQL exception should point to non0existing Accout field'
    );
  }

  /***********************************

***********************************/
  @isTest
  static void testMakeQuery() {
    String field = 'TerritoryGeo__c';
    String op = 'EQUAL';
    String valu = 'APAC';

    String expected = '( TerritoryGeo__c = \'' + valu + '\' )';
    String retval = TerritoryBuilderHelper.MakeSOQL(field, op, valu);
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );
  }
  /****************************************
   pass String filed  and Numeric
   pass ULL val  and not null
****************************************/
  @isTest
  static void testEQUALNOTEQUAL() {
    String field = 'TerritoryGeo__c';
    String valu = 'APAC';
    String fType = 'STRING';

    String expected = '( TerritoryGeo__c = \'' + valu + '\' )';
    String retval = TerritoryBuilderHelper.BuildEqualSOQL(
      field,
      valu,
      ftype,
      false
    );
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );

    expected = '( TerritoryGeo__c != \'' + valu + '\' )';
    retval = TerritoryBuilderHelper.BuildEqualSOQL(field, valu, ftype, true);
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );

    field = 'Employee_Count__c';
    valu = '10';
    fType = 'NUMERIC';

    expected = '( Employee_Count__c != ' + valu + ' )';
    retval = TerritoryBuilderHelper.BuildEqualSOQL(field, valu, ftype, true);
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );

    valu = null;

    expected = '( Employee_Count__c = null )';
    retval = TerritoryBuilderHelper.BuildEqualSOQL(field, valu, ftype, false);
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );
  }

  /**********************************

**********************************/
  @isTest
  static void testGRELESS() {
    String field = 'Employee_Count__c';
    String valu = '10';
    String expected = '( Employee_Count__c > ' + valu + ' )';
    String retval = TerritoryBuilderHelper.Build_GRELESS_SOQL(
      field,
      valu,
      true
    );
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );

    expected = '( Employee_Count__c < ' + valu + ' )';
    retval = TerritoryBuilderHelper.Build_GRELESS_SOQL(field, valu, false);
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );
  }

  /*********************************

*********************************/
  @isTest
  static void testBETWEEN() {
    String field = 'Employee_Count__c';
    String valu = '10;20';
    String expected = '( Employee_Count__c > 10 AND Employee_Count__c < 20 )';
    String retval = TerritoryBuilderHelper.Build_BETWEEN_SOQL(
      field,
      valu,
      false
    );
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );

    expected = '( Employee_Count__c < 10 AND Employee_Count__c > 20 )';
    retval = TerritoryBuilderHelper.Build_BETWEEN_SOQL(field, valu, true);
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );
  }

  /**********************************

**********************************/
  @isTest
  static void testINNOTIN() {
    String field = 'TerritoryGeo__c';
    String valu = 'T1,T2';
    String expected = 'TerritoryGeo__c IN ( \'T1\',\'T2\' )';
    String retval = TerritoryBuilderHelper.Build_IN_SOQL(field, valu, false);
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );

    expected = '( NOT TerritoryGeo__c IN ( \'T1\',\'T2\' ) )';
    retval = TerritoryBuilderHelper.Build_IN_SOQL(field, valu, true);
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );
  }

  /********************************
   Build_ISNULL_SOQL(String field)
********************************/
  @isTest
  static void testISNULL() {
    String field = 'TerritoryGeo__c';
    String expected = '( TerritoryGeo__c = NULL )';
    String retval = TerritoryBuilderHelper.Build_IS_NOT_NULL_SOQL(field, '=');
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );

    expected = '( TerritoryGeo__c != NULL )';
    retval = TerritoryBuilderHelper.Build_IS_NOT_NULL_SOQL(field, '!=');
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );
  }

  /******************************

******************************/
  @isTest
  static void testLIKE() {
    String field = 'TerritoryGeo__c';
    String valu = 'AP';
    String expected = '( TerritoryGeo__c Like \'AP%\' )';
    String retval = TerritoryBuilderHelper.Build_LIKE_SOQL(
      field,
      valu,
      'STARTS_WITH'
    );

    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );

    expected = '( TerritoryGeo__c Like \'%AP\' )';
    retval = TerritoryBuilderHelper.Build_LIKE_SOQL(field, valu, 'END_WITH');
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );

    expected = '( TerritoryGeo__c Like \'%AP%\' )';
    retval = TerritoryBuilderHelper.Build_LIKE_SOQL(field, valu, 'CONTAINS');
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );

    expected = '( NOT TerritoryGeo__c Like \'%AP%\' )';
    retval = TerritoryBuilderHelper.Build_LIKE_SOQL(
      field,
      valu,
      'NOT_CONTAINS'
    );
    System.AssertEquals(
      expected,
      retval,
      'Expect Build SQL to match the field/op/value'
    );
  }

  @isTest
  static void testPlayWihtPropagate() {
    //creater 1 TA and play with different field to increase coverage
    ID allocRT = Schema.SObjectType.TerritoryAllocator__c.getRecordTypeInfosByDeveloperName()
      .get('NODE')
      .getRecordTypeId();
    TerritoryAllocator__c theTOPGEONODE1 = (TerritoryAllocator__c) TestFactory.createSObject(
      new TerritoryAllocator__c(
        Name = 'TOP_GEO_NODE1',
        Geo__c = 'NORAM',
        Account_field__c = 'TerritoryGeo__c',
        Operator__c = 'EQUAL',
        Comparison_Value__c = 'NORAM',
        Validate__c = true,
        RecordTypeId = allocRT
      ),
      true
    );
    TerritoryAllocator__c theSEGMENTNODE1 = (TerritoryAllocator__c) TestFactory.createSObject(
      new TerritoryAllocator__c(
        Name = 'SEGMENT_NODE',
        Geo__c = 'NORAM',
        Account_field__c = 'TerritorySegment__c',
        Operator__c = 'EQUAL',
        Comparison_Value__c = 'HIED',
        ParentAllocator__c = theTOPGEONODE1.id,
        Validate__c = true,
        RecordTypeId = allocRT
      ),
      true
    );
    TerritoryAllocator__c theBOTTOMNODE1 = (TerritoryAllocator__c) TestFactory.createSObject(
      new TerritoryAllocator__c(
        Name = 'BOTTOM_NODE1',
        Geo__c = 'NORAM',
        Account_field__c = 'Org_Type__c',
        Operator__c = 'EQUAL',
        Comparison_Value__c = 'Corporate',
        ParentAllocator__c = theSEGMENTNODE1.id,
        Validate__c = true,
        isBottom__c = true,
        Territory_Name__c = 'TERR1',
        Order_of_Execution__c = 301,
        RecordTypeId = allocRT
      ),
      true
    );

    //clear the bottom node  BuildQuery then try  to set forcePropagate for the top
    theBOTTOMNODE1 = [
      SELECT Built_SOQL__c
      FROM TerritoryAllocator__c
      WHERE id = :theBOTTOMNODE1.id
    ];
    String theBQ = theBOTTOMNODE1.Built_SOQL__c;
    theBOTTOMNODE1.Built_SOQL__c = null;
    update theBOTTOMNODE1;

    theTOPGEONODE1.Validate__c = true;
    update theTOPGEONODE1;

    theBOTTOMNODE1 = [
      SELECT Built_SOQL__c
      FROM TerritoryAllocator__c
      WHERE id = :theBOTTOMNODE1.id
    ];
    System.AssertEquals(
      theBQ,
      theBOTTOMNODE1.Built_SOQL__c,
      'Update should re-create the Node  Biuld SQL field'
    );
  }

  @istest
  static void playWithCustomSplitted() {
    ID allocRT = Schema.SObjectType.TerritoryAllocator__c.getRecordTypeInfosByDeveloperName()
      .get('NODE')
      .getRecordTypeId();

    TerritoryAllocator__c theTOPGEONODE1 = (TerritoryAllocator__c) TestFactory.createSObject(
      new TerritoryAllocator__c(
        Name = 'TOP_GEO_NODE1',
        Geo__c = 'NORAM',
        Account_field__c = 'TerritoryGeo__c',
        Operator__c = 'EQUAL',
        Comparison_Value__c = 'NORAM',
        Validate__c = true,
        RecordTypeId = allocRT
      ),
      true
    );
    TerritoryAllocator__c theSEGMENTNODE1 = (TerritoryAllocator__c) TestFactory.createSObject(
      new TerritoryAllocator__c(
        Name = 'SEGMENT_NODE3',
        Geo__c = 'NORAM',
        Account_field__c = 'TerritorySegment__c',
        Operator__c = 'EQUAL',
        Comparison_Value__c = 'MM',
        ParentAllocator__c = theTOPGEONODE1.id,
        Validate__c = true,
        RecordTypeId = allocRT
      ),
      true
    );
    TerritoryAllocator__c theSplittedNode = new TerritoryAllocator__c(
      Name = 'theSplittedNode',
      Geo__c = 'NORAM',
      Account_field__c = 'Org_Type__c',
      Operator__c = 'IN_SPLITTEDITEM',
      ParentAllocator__c = theSEGMENTNODE1.id,
      RecordtypeId = allocRT,
      Type__c = 'CUSTOM_SPLITTED',
      Local_SOQL__c = 'Org_Type__c IN (\'item1\',\'Corporate\')'
    );
    theSplittedNode = (TerritoryAllocator__c) TestFactory.createSObject(
      theSplittedNode,
      true
    );

    TerritoryAllocatorItem__c theSplittedItem1 = new TerritoryAllocatorItem__c();
    theSplittedItem1.Active__c = true;
    theSplittedItem1.Allocator__c = theSplittedNode.id;
    theSplittedItem1.Field__c = 'Org_Type__c';
    theSplittedItem1.Item_Value__c = 'item1';
    theSplittedItem1 = (TerritoryAllocatorItem__c) TestFactory.createSObject(
      theSplittedItem1,
      true
    );

    TerritoryAllocatorItem__c theSplittedItem2 = new TerritoryAllocatorItem__c();
    theSplittedItem2.Active__c = true;
    theSplittedItem2.Allocator__c = theSplittedNode.id;
    theSplittedItem2.Field__c = 'Org_Type__c';
    theSplittedItem2.Item_Value__c = 'Corporate';
    theSplittedItem2 = (TerritoryAllocatorItem__c) TestFactory.createSObject(
      theSplittedItem2,
      true
    );
    //once items created Validater te splitted node and make it Bottom
    theSplittedNode.Territory_Name__c = 'TERR3';
    theSplittedNode.Order_of_Execution__c = 303;
    theSplittedNode.isBottom__c = true;
    theSplittedNode.Validate__c = true;

    update theSplittedNode;

    String expected = '( TerritoryGeo__c = \'NORAM\' ) AND ( TerritorySegment__c = \'MM\' ) AND Org_Type__c IN ( \'Corporate\',\'item1\' )';
    theSplittedNode = [
      SELECT id, Built_SOQL__c
      FROM TerritoryAllocator__c
      WHERE id = :theSplittedNode.id
    ];
    String expectedBQ = theSplittedNode.Built_SOQL__c;
    System.AssertEquals(
      ExpectedBQ,
      expected,
      'Expect to pull filter condition from the HUB\'s Items'
    );

    //clear the theSplittedNode Build_SQL and Validate Top Node
    theSplittedNode.Built_SOQL__c = null;
    update theSplittedNode;

    theTOPGEONODE1.Validate__c = true;
    update theTOPGEONODE1;
    theSplittedNode = [
      SELECT id, Built_SOQL__c
      FROM TerritoryAllocator__c
      WHERE id = :theSplittedNode.id
    ];
    System.AssertEquals(
      ExpectedBQ,
      theSplittedNode.Built_SOQL__c,
      'if parent node is re-validated child nodes should re-calculate'
    );
  }

  @isTest
  static void testvalidateMarketSegment() {
    List<TerritoryAllocator__c> tAs = new List<TerritoryAllocator__c>();

    ID allocRT = Schema.SObjectType.TerritoryAllocator__c.getRecordTypeInfosByDeveloperName()
      .get('NODE')
      .getRecordTypeId();

    //create several bottom territoties  according to  configuration in  method TerritoryBuilderHelper.setTerrMarket
    TerritoryAllocator__c theTA1 = (TerritoryAllocator__c) TestFactory.createSObject(
      new TerritoryAllocator__c(
        Name = 'BOTTOM_NODE1',
        Geo__c = 'NORAM',
        Account_field__c = 'Org_Type__c',
        Operator__c = 'EQUAL',
        Comparison_Value__c = 'Corporate',
        Validate__c = true,
        isBottom__c = true,
        Territory_Name__c = 'NORAM CORP ENT',
        Order_of_Execution__c = 301,
        RecordTypeId = allocRT
      ),
      true
    );
    TerritoryAllocator__c tA2 = (TerritoryAllocator__c) TestFactory.createSObject(
      new TerritoryAllocator__c(
        Name = 'BOTTOM_NODE2',
        Geo__c = 'LATAM',
        Account_field__c = 'Org_Type__c',
        Operator__c = 'EQUAL',
        Comparison_Value__c = 'Corporate',
        Validate__c = true,
        isBottom__c = true,
        Territory_Name__c = 'LATAM_TERR',
        Order_of_Execution__c = 201,
        RecordTypeId = allocRT
      ),
      true
    );
    TerritoryAllocator__c tA3 = (TerritoryAllocator__c) TestFactory.createSObject(
      new TerritoryAllocator__c(
        Name = 'BOTTOM_NODE3',
        Geo__c = 'APAC',
        Account_field__c = 'Org_Type__c',
        Operator__c = 'EQUAL',
        Comparison_Value__c = 'Corporate',
        Validate__c = true,
        isBottom__c = true,
        Territory_Name__c = 'APAC CORP',
        Order_of_Execution__c = 101,
        RecordTypeId = allocRT
      ),
      true
    );

    TerritoryAllocator__c tA4 = (TerritoryAllocator__c) TestFactory.createSObject(
      new TerritoryAllocator__c(
        Name = 'BOTTOM_NODE4',
        Geo__c = 'NORAM',
        Account_field__c = 'Org_Type__c',
        Operator__c = 'EQUAL',
        Comparison_Value__c = 'Corporate',
        Validate__c = true,
        isBottom__c = true,
        Territory_Name__c = 'NORAM HIED',
        Order_of_Execution__c = 304,
        RecordTypeId = allocRT
      ),
      true
    );
    TerritoryAllocator__c tA5 = (TerritoryAllocator__c) TestFactory.createSObject(
      new TerritoryAllocator__c(
        Name = 'BOTTOM_NODE5',
        Geo__c = 'NORAM',
        Account_field__c = 'Org_Type__c',
        Operator__c = 'EQUAL',
        Comparison_Value__c = 'Corporate',
        Validate__c = true,
        isBottom__c = true,
        Territory_Name__c = 'NORAM K12',
        Order_of_Execution__c = 305,
        RecordTypeId = allocRT
      ),
      true
    );
    TerritoryAllocator__c tA6 = (TerritoryAllocator__c) TestFactory.createSObject(
      new TerritoryAllocator__c(
        Name = 'BOTTOM_NODE6',
        Geo__c = 'NORAM',
        Account_field__c = 'Org_Type__c',
        Operator__c = 'EQUAL',
        Comparison_Value__c = 'Corporate',
        Validate__c = true,
        isBottom__c = true,
        Territory_Name__c = 'NORAM Enterprise',
        Order_of_Execution__c = 306,
        RecordTypeId = allocRT
      ),
      true
    );

    TAs.add(theTA1);
    TAs.add(tA2);
    TAs.add(tA3);
    TAs.add(tA4);
    TAs.add(tA5);
    TAs.add(tA6);

    TAs = [
      SELECT
        Name,
        isBottom__c,
        Territory_Name__c,
        TerritoryTeam__c,
        Territory_Market__c,
        Segment__c,
        Geo__c
      FROM TerritoryAllocator__c
    ];

    ValidateTerritoryMarket(TAs);
    ValidateTerritorySegment(TAs);

    System.assert(
      true,
      'Hello PDM. the asserts are in the above 2 methods so do not complain.'
    );
  }

  /*********************************************************************************
  this is not a test method. It  is called from test methods and we do assert here.
  *********************************************************************************/
  public static void validateTerritoryMarket(
    List<TerritoryAllocator__c> theTAs
  ) {
    String market2Match;
    for (TerritoryAllocator__c theTA : theTAs) {
      if (theTA.isBottom__c == false) {
        continue;
      }

      if (theTA.Geo__c == 'LATAM') {
        market2Match = 'EDU';
      }

      if (
        theTA.Geo__c == 'APAC' &&
        (theTA.territory_Name__c != null &&
        theTA.territory_Name__c.contains('CORP') ||
        (theTA.TerritoryTeam__c != null &&
        theTA.TerritoryTeam__c.contains('CORP')))
      ) {
        market2Match = 'CORP';
      }

      if (
        (theTA.territory_Name__c != null &&
        theTA.territory_Name__c.contains('HIED')) ||
        (theTA.TerritoryTeam__c != null &&
        theTA.TerritoryTeam__c.contains('HIED'))
      ) {
        Market2Match = 'EDU';
      }

      if (
        (theTA.territory_Name__c != null &&
        theTA.territory_Name__c.contains('K12')) ||
        (theTA.TerritoryTeam__c != null &&
        theTA.TerritoryTeam__c.contains('K12'))
      ) {
        Market2Match = 'EDU';
      }

      if (
        theTA.Geo__c == 'NORAM' &&
        ((theTA.territory_Name__c != null &&
        theTA.territory_Name__c.contains('Enterprise')) ||
        (theTA.TerritoryTeam__c != null &&
        theTA.TerritoryTeam__c.contains('ENT')))
      ) {
        Market2Match = 'CORP';
      }

      if (
        theTA.Geo__c == 'NORAM' &&
        (theTA.territory_Name__c != null &&
        theTA.territory_Name__c.contains('NORAM CORP ENT')) ||
        (theTA.TerritoryTeam__c != null &&
        (theTA.TerritoryTeam__c.contains('SME') ||
        theTA.TerritoryTeam__c.contains('MM')))
      ) {
        Market2Match = 'CORP';
      }

      if (
        (theTA.territory_Name__c != null &&
        theTA.territory_Name__c.contains('RTO')) ||
        (theTA.TerritoryTeam__c != null &&
        theTA.TerritoryTeam__c.contains('RTO'))
      ) {
        Market2Match = 'EDU';
      }

      if (
        theTA.TerritoryTeam__c != null &&
        (theTA.TerritoryTeam__c == 'EMEA EDU ENT' ||
        theTA.TerritoryTeam__c == 'EMEA EDU MM UK' ||
        theTA.TerritoryTeam__c == 'EMEA EDU MM EMERG' ||
        theTA.TerritoryTeam__c == 'EMEA EDU MM BENONORD' ||
        theTA.TerritoryTeam__c == 'EMEA EDU INSIDE')
      ) {
        Market2Match = 'EDU';
      }

      if (
        theTA.TerritoryTeam__c != null &&
        (theTA.TerritoryTeam__c == 'EMEA CORP ENT 1' ||
        theTA.TerritoryTeam__c == 'EMEA CORP MM' ||
        theTA.TerritoryTeam__c == 'EMEA CORP ENT 2' ||
        theTA.TerritoryTeam__c == 'EMEA CORP IS')
      ) {
        Market2Match = 'CORP';
      }

      System.assertNotEquals(
        Market2Match,
        null,
        'Accoutn MArket value shuld not be NULL'
      );
      System.assertEquals(Market2Match, theTA.territory_Market__c, theTA);
    }
  }

  /********************************************************************************
  this is not a test method. It  is called from test methods and we do assert here.
  ********************************************************************************/
  public static void validateTerritorySegment(
    List<TerritoryAllocator__c> theTAs
  ) {
    String segment2Match;
    for (TerritoryAllocator__c theTA : theTAs) {
      if (theTA.isBottom__c == false) {
        continue; //do this only for Bottom
      }

      if (theTA.Geo__c == 'LATAM') {
        segment2Match = 'HIED';
        System.assertEquals(Segment2Match, theTA.Segment__c, theTA);
        continue;
      }

      if (
        theTA.Geo__c == 'APAC' &&
        ((theTA.territory_Name__c != null &&
        theTA.territory_Name__c.contains('CORP')) ||
        (theTA.TerritoryTeam__c != null &&
        theTA.TerritoryTeam__c.contains('CORP')))
      ) {
        Segment2Match = 'CORP';
        System.assertEquals(Segment2Match, theTA.Segment__c, theTA);
        continue;
      }

      if (
        theTA.territory_Name__c != null &&
        theTA.territory_Name__c.contains('HIED') ||
        theTA.TerritoryTeam__c != null &&
        theTA.TerritoryTeam__c.contains('HIED')
      ) {
        Segment2Match = 'HIED';
        System.assertEquals(Segment2Match, theTA.Segment__c, theTA);
        continue;
      }

      if (
        theTA.territory_Name__c != null &&
        theTA.territory_Name__c.contains('K12') ||
        theTA.TerritoryTeam__c != null && theTA.TerritoryTeam__c.contains('K12')
      ) {
        Segment2Match = 'K12';
        System.assertEquals(Segment2Match, theTA.Segment__c, theTA);
        continue;
      }

      if (
        theTA.Geo__c == 'NORAM' &&
        ((theTA.territory_Name__c != null &&
        theTA.territory_Name__c.contains('Enterprise')) ||
        (theTA.TerritoryTeam__c != null &&
        theTA.TerritoryTeam__c.contains('ENT')))
      ) {
        Segment2Match = 'ENT';
        System.assertEquals(Segment2Match, theTA.Segment__c, theTA);
        continue;
      }

      if (
        theTA.Geo__c == 'NORAM' &&
        (theTA.TerritoryTeam__c != null &&
        (theTA.TerritoryTeam__c.contains('MM') ||
        theTA.TerritoryTeam__c.contains('SME')))
      ) {
        Segment2Match = 'MM';
        System.assertEquals(Segment2Match, theTA.Segment__c, theTA);
        continue;
      }

      if (
        theTA.Geo__c == 'NORAM' &&
        theTA.TerritoryTeam__c != null &&
        theTA.TerritoryTeam__c.contains('NORAM CORP ENT')
      ) {
        Segment2Match = 'ENT';
        System.assertEquals(Segment2Match, theTA.Segment__c, theTA);
        continue;
      }

      if (
        (theTA.territory_Name__c != null &&
        theTA.territory_Name__c.contains('RTO')) ||
        (theTA.TerritoryTeam__c != null &&
        theTA.TerritoryTeam__c.contains('RTO'))
      ) {
        Segment2Match = 'RTO';
        System.assertEquals(Segment2Match, theTA.Segment__c, theTA);
        continue;
      }

      //INCLUDE EMEA rule here too
      if (theTA.TerritoryTeam__c == 'EMEA EDU ENT') {
        Segment2Match = 'ENT';
      }
      if (
        theTA.TerritoryTeam__c == 'EMEA EDU MM UK' ||
        theTA.TerritoryTeam__c == 'EMEA EDU MM BENONORD' ||
        theTA.TerritoryTeam__c == 'EMEA EDU MM EMERG' ||
        theTA.TerritoryTeam__c == 'EMEA EDU INSIDE'
      ) {
        Segment2Match = 'MM';
      }
      if (
        theTA.TerritoryTeam__c == 'EMEA CORP ENT 1' ||
        theTA.TerritoryTeam__c == 'EMEA CORP MM'
      ) {
        Segment2Match = 'ENT 1';
      }
      if (theTA.TerritoryTeam__c == 'EMEA CORP ENT 2') {
        Segment2Match = 'ENT 2';
      }
      if (theTA.TerritoryTeam__c == 'EMEA CORP IS') {
        Segment2Match = 'IS';
      }

      System.assertEquals(Segment2Match, theTA.Segment__c, theTA);
      continue;
    }
  }
}