force-app/main/default/objects/Batch_Job_Monitor__c/Batch_Job_Monitor__c.object-meta.xml
<CustomObject>
    <description>object use tomtrack  batch class statistic</description>
    <label>Batch Job Monitor</label>
    <nameField>
        <displayFormat>BJM-{YYMMDD}-{000}</displayFormat>
        <label>Batch Job Monitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BatchJobMonitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if active create child monitor records</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/BatchClassName__c.field-meta.xml
<CustomField>
    <fullName>BatchClassName__c</fullName>
    <label>BatchClassName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/BatchJobID__c.field-meta.xml
<CustomField>
    <fullName>BatchJobID__c</fullName>
    <externalId>true</externalId>
    <label>BatchJobID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/Parent_BatchMonitor__c.field-meta.xml
<CustomField>
    <fullName>Parent_BatchMonitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent BatchMonitor</label>
    <referenceTo>Batch_Job_Monitor__c</referenceTo>
    <relationshipLabel>BatchJobMonitors</relationshipLabel>
    <relationshipName>BatchJobMonitors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor_Item__c/Batch_Job_Monitor_Item__c.object-meta.xml
<CustomObject>
    <label>Batch Job Monitor Item</label>
    <nameField>
        <displayFormat>BJMI-{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>Batch Job Monitor Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BatchJobMonitorItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/batchPlatformEvErrorTriggerXHandler.cls
public without sharing class batchPlatformEvErrorTriggerXHandler extends TriggerX {
  public batchPlatformEvErrorTriggerXHandler() {
  }

  public override void onAfterInsert() {
    //hopefully 1 insert  will came from the same Apex
    Set<Id> asyncApexJobIds = new Set<Id>();
    for (BatchApexErrorEvent evt : (List<BatchApexErrorEvent>) records) {
      asyncApexJobIds.add(evt.AsyncApexJobId);
    }

    map<ID, ID> mapBJId2BJMID = new Map<ID, ID>();
    Set<ID> batchJobId = new Set<ID>();
    List<Batch_Job_Monitor__C> bjms = [
      SELECT
        id,
        BatchJobID__c,
        BatchClassName__c,
        Parent_BatchMonitor__r.Active__c,
        Parent_BatchMonitor__r.Log_Level__c
      FROM Batch_Job_Monitor__C
      WHERE
        BatchJobID__c IN :asyncApexJobIds
        AND Parent_BatchMonitor__r.Log_Level__c = 'High'
    ];
    if (bjms.size() == 0) {
      return;
    }

    for (Batch_Job_Monitor__C bjm : bjms) {
      batchJobId.add(bjm.BatchJobID__c);
      mapBJId2BJMID.put(bjm.BatchJobID__c, bjm.Id);
    }
    List<Batch_Job_Monitor_Item__c> bjmis = new List<Batch_Job_Monitor_Item__c>();
    for (BatchApexErrorEvent evt : (List<BatchApexErrorEvent>) records) {
      //only handle events for the job(s) we care about
      if (mapBJId2BJMID.keyset().contains(evt.AsyncApexJobId)) {
        ID bjmID = mapBJId2BJMID.get(evt.AsyncApexJobId);

        if (evt.JobScope == null) {
          Batch_Job_Monitor_Item__c bjmiNE = batchProcessAccountAlocator.createBatchMonitorItem(
            bjmID,
            evt.Message,
            evt.Phase,
            'No record'
          );
          BJMIs.add(bjmiNE);
          continue;
        }

        for (String item : evt.JobScope.split(',')) {
          //try to create here a BJM_Item records based on ect fields
          Batch_Job_Monitor_Item__c bjmi = batchProcessAccountAlocator.createBatchMonitorItem(
            bjmID,
            evt.Message,
            evt.Phase,
            item
          );
          BJMIs.add(bjmi);
        }
      }
    }

    if (BJMIs.size() > 0) {
      Database.insert(BJMIs, false);
    }
  }
}