force-app/main/default/objects/Account/fields/FreezeAlignment__c.field-meta.xml
<CustomField>
    <fullName>FreezeAlignment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If  set to TRUE  do no longer attempt to Set Territory Name</description>
    <label>FreezeAlignment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Need_Alignment__c.field-meta.xml
<CustomField>
    <fullName>Need_Alignment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need Alignment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/temp_AllocatorID__c.field-meta.xml
<CustomField>
    <fullName>temp_AllocatorID__c</fullName>
    <description>used in Terr alignment logic</description>
    <label>temp AllocatorID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TerritoryName_Suggested__c.field-meta.xml
<CustomField>
    <fullName>TerritoryName_Suggested__c</fullName>
    <description>Suggeste territory name</description>
    <label>TerritoryName Suggested</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FIND SUGGESTION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/Batch_Job_Monitor__c.object-meta.xml
<CustomObject>
    <description>object use tomtrack  batch class statistic</description>
    <label>Batch Job Monitor</label>
    <nameField>
        <displayFormat>BJM-{YYMMDD}-{000}</displayFormat>
        <label>Batch Job Monitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BatchJobMonitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if active create child monitor records</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/BatchClassName__c.field-meta.xml
<CustomField>
    <fullName>BatchClassName__c</fullName>
    <label>BatchClassName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/recordTypes/Header.recordType-meta.xml
<RecordType>
    <fullName>Header</fullName>
    <active>true</active>
    <label>Header</label>
</RecordType>

force-app/main/default/objects/Batch_Job_Monitor_Item__c/Batch_Job_Monitor_Item__c.object-meta.xml
<CustomObject>
    <label>Batch Job Monitor Item</label>
    <nameField>
        <displayFormat>BJMI-{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>Batch Job Monitor Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BatchJobMonitorItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Job_Monitor_Item__c/fields/Parent_Job_Monitor__c.field-meta.xml
<CustomField>
    <fullName>Parent_Job_Monitor__c</fullName>
    <label>Parent Job Monitor</label>
    <referenceTo>Batch_Job_Monitor__c</referenceTo>
    <relationshipLabel>BatchJobMonitorItems</relationshipLabel>
    <relationshipName>BatchJobMonitorItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/TerritoryAllocator__c.object-meta.xml
<CustomObject>
    <label>TerritoryAllocator</label>
    <nameField>
        <label>TerritoryAllocator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TerritoryAllocators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TerritoryAllocator__c/fields/Account_field__c.field-meta.xml
<CustomField>
    <fullName>Account_field__c</fullName>
    <description>Accout filed  to compare  with</description>
    <label>Account field</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Comparison_Value__c.field-meta.xml
<CustomField>
    <fullName>Comparison_Value__c</fullName>
    <label>Comparison Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Geo__c.field-meta.xml
<CustomField>
    <fullName>Geo__c</fullName>
    <label>Geo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>NORAM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/isBottom__c.field-meta.xml
<CustomField>
    <fullName>isBottom__c</fullName>
    <defaultValue>false</defaultValue>
    <description>specify  if this  record corresponds to the bottom territory branch</description>
    <label>isBottom</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EQUAL</fullName>
            </value>
            <value>
                <fullName>NOT_EQUAL</fullName>
            </value>
            <value>
                <fullName>GREATER</fullName>
            </value>
            <value>
                <fullName>LESS</fullName>
            </value>
            <value>
                <fullName>STARTS_WITH</fullName>
            </value>
            <value>
                <fullName>END_WITH</fullName>
            </value>
            <value>
                <fullName>CONTAINS</fullName>
            </value>
            <value>
                <fullName>BETWEEN</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>NOT_IN</fullName>
            </value>
            <value>
                <fullName>IN_SPLITTEDITEM</fullName>
            </value>
            <value>
                <fullName>ISNULL</fullName>
            </value>
            <value>
                <fullName>NOT_BETWEEN</fullName>
            </value>
            <value>
                <fullName>NOT_CONTAINS</fullName>
            </value>
            <value>
                <fullName>NOTNULL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Order_of_Execution__c.field-meta.xml
<CustomField>
    <fullName>Order_of_Execution__c</fullName>
    <description>when runnign batches for Territory this is the order of the territory specific batch in th chain</description>
    <label>Order of Execution</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/ParentAllocator__c.field-meta.xml
<CustomField>
    <fullName>ParentAllocator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ParentAllocator</label>
    <referenceTo>TerritoryAllocator__c</referenceTo>
    <relationshipLabel>TerritoryAllocators</relationshipLabel>
    <relationshipName>TerritoryAllocators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/TerritoryTeam__c.field-meta.xml
<CustomField>
    <fullName>TerritoryTeam__c</fullName>
    <label>TerritoryTeam</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NORAM HIED East</fullName>
            </value>
            <value>
                <fullName>NORAM HIED West</fullName>
            </value>
            <value>
                <fullName>NORAM HIED Central</fullName>
            </value>
            <value>
                <fullName>NORAM K12 East</fullName>
            </value>
            <value>
                <fullName>NORAM K12 Central</fullName>
            </value>
            <value>
                <fullName>NORAM CORP ENT</fullName>
            </value>
            <value>
                <fullName>NORAM CORP MM 1</fullName>
            </value>
            <value>
                <fullName>NORAM CORP MM 2</fullName>
            </value>
            <value>
                <fullName>NORAM CORP SME 1</fullName>
            </value>
            <value>
                <fullName>LATAM HIED Spanish</fullName>
            </value>
            <value>
                <fullName>LATAM HIED Brazil</fullName>
            </value>
            <value>
                <fullName>HIED AUSNZ</fullName>
            </value>
            <value>
                <fullName>HIED ASIA</fullName>
            </value>
            <value>
                <fullName>K12 AUSNZ</fullName>
            </value>
            <value>
                <fullName>RTO AUSNZ</fullName>
            </value>
            <value>
                <fullName>APAC CORP</fullName>
            </value>
            <value>
                <fullName>EMEA EDU ENT</fullName>
            </value>
            <value>
                <fullName>EMEA EDU MM UK</fullName>
            </value>
            <value>
                <fullName>EMEA EDU MM BENONORD</fullName>
            </value>
            <value>
                <fullName>EMEA EDU MM EMERG</fullName>
            </value>
            <value>
                <fullName>EMEA EDU INSIDE</fullName>
            </value>
            <value>
                <fullName>EMEA CORP ENT 1</fullName>
            </value>
            <value>
                <fullName>EMEA CORP MM</fullName>
            </value>
            <value>
                <fullName>EMEA CORP IS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/fields/Validate__c.field-meta.xml
<CustomField>
    <fullName>Validate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if  checked  on update we validate the Query then we clear this flag.</description>
    <label>Validate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TerritoryAllocator__c/recordTypes/NODE.recordType-meta.xml
<RecordType>
    <fullName>NODE</fullName>
    <active>true</active>
    <description>Allocator record which define its own Local query Can have HUB or NODE as children. No HUB Item</description>
    <label>NODE</label>
</RecordType>

force-app/main/default/classes/batchProcessAccountTerritory_Test.cls
@istest
public class batchProcessAccountTerritory_Test {
  @testSetup
  static void testSetup() {
    List<System_Country_Validation_Record__c> countries = new List<System_Country_Validation_Record__c>();
    countries.add(
      new System_Country_Validation_Record__c(
        Name = 'United States',
        Country_Code__c = 'US',
        Region__c = 'DOMESTIC'
      )
    );
    countries.add(
      new System_Country_Validation_Record__c(
        Name = 'Argentina',
        Country_Code__c = 'AR',
        Region__c = 'LATAM'
      )
    );
    countries.add(
      new System_Country_Validation_Record__c(
        Name = 'Singapore',
        Country_Code__c = 'SG',
        Region__c = 'APAC'
      )
    );
    countries.add(
      new System_Country_Validation_Record__c(
        Name = 'Portugal',
        Country_Code__c = 'PT',
        Region__c = 'EMEA'
      )
    );
    insert countries;

    ID nodeRT = Schema.SObjectType.TerritoryAllocator__c.getRecordTypeInfosByName()
      .get('NODE')
      .getRecordTypeId();

    /****************************************** create a 3 Nodes  **************************/
    TerritoryAllocator__c theTOPGEONODE1 = (TerritoryAllocator__c) TestFactory.createSObject(
      new TerritoryAllocator__c(
        Name = 'TOP_GEO_NODE1',
        Geo__c = 'NORAM',
        Account_field__c = 'TerritoryGeo__c',
        Operator__c = 'EQUAL',
        Comparison_Value__c = 'NORAM',
        Validate__c = true,
        RecordTypeId = nodeRT
      ),
      true
    );
    TerritoryAllocator__c theSEGMENTNODE1 = (TerritoryAllocator__c) TestFactory.createSObject(
      new TerritoryAllocator__c(
        Name = 'SEGMENT_NODE',
        Geo__c = 'NORAM',
        Account_field__c = 'TerritorySegment__c',
        Operator__c = 'EQUAL',
        Comparison_Value__c = 'HIED',
        ParentAllocator__c = theTOPGEONODE1.id,
        Validate__c = true,
        RecordTypeId = NodeRT
      ),
      true
    );
    TerritoryAllocator__c theBOTTOMNODE1 = (TerritoryAllocator__c) TestFactory.createSObject(
      new TerritoryAllocator__c(
        Name = 'BOTTOM_NODE1',
        Geo__c = 'NORAM',
        Account_field__c = 'Org_Type__c',
        Operator__c = 'EQUAL',
        Comparison_Value__c = 'Corporate',
        ParentAllocator__c = theSEGMENTNODE1.id,
        Validate__c = true,
        isBottom__c = true,
        Territory_Name__c = 'NORAM HIED Great Lakes',
        Order_of_Execution__c = 301,
        RecordTypeId = NodeRT
      ),
      true
    );
    /******************************************* create a 3 Node  ***********************************************/

    //create 1 account which match
    Account theA2M = new Account(Name = 'TestAccM');
    theA2M.TerritoryGeo__c = 'NORAM';
    theA2M.ShippingCountry = 'United States';
    theA2M.Org_Type__c = 'Corporate';
    theA2M.ShippingPostalCode = '123456';
    theA2M.TerritorySegment__c = 'HIED';
    theA2M = (Account) TestFactory.createSObject(theA2M, true);
    System.assertEquals(true, theA2M.id != null, 'Account should exist');

    //create 1 account which does not match
    Account theA2NM = new Account(Name = 'TestAccNM');
    theA2NM.TerritoryGeo__c = 'NORAM';
    theA2NM.ShippingCountry = 'United States';
    theA2NM.Org_Type__c = 'K12';
    theA2NM.ShippingPostalCode = '234561';
    theA2NM.TerritorySegment__c = 'HIED';
    theA2NM = (Account) TestFactory.createSObject(theA2NM, true);
    System.assertEquals(true, theA2NM.id != null, 'Account should exist');
  }

  @isTest
  static void testbatchAllocatorExecute() {
    Batch_Job_Monitor__c headeru = new Batch_Job_Monitor__c();
    headeru.BatchClassName__c = 'batchProcessAccountTerritory';
    headeru.Active__c = true;
    headeru.Log_Level__c = 'High';
    insert headeru;

    //create 1 account which is frozen
    Account theAF = new Account(Name = 'TestAccF');
    theAF.TerritoryGeo__c = 'NORAM';
    theAF.ShippingCountry = 'United States';
    theAF.Org_Type__c = 'Other';
    theAF.ShippingPostalCode = '654321';
    theAF.TerritorySegment__c = 'K12';
    theAF.temp_AllocatorID__c = 'NORAM K12 East/EDU/K12';
    theAF = (Account) TestFactory.createSObject(theAF, true);
    System.assertEquals(
      true,
      theAF.id != null,
      'Account should have been created'
    );

    //add oportunity to this Account
    Opportunity theO = new Opportunity();
    theO.AccountId = theAF.id;
    theO.stageName = 'Needs Approval';
    theO.CloseDate = System.Date.today().addDays(2);
    theO = (Opportunity) TestFactory.createSObject(theO, true);

    List<TerritoryAllocator__c> tas = [SELECT id FROM TerritoryAllocator__c];
    system.assertEquals(
      3,
      tas.size(),
      'We check if the 3 Allocator records were created succesfully in TestSetup'
    );

    batchProcessAccountTerritory batchu;
    Test.startTest();

    batchu = new batchProcessAccountTerritory('NORAM', null, null);
    DataBase.executeBatch(batchu);

    Test.stopTest();

    List<Account> accs = [
      SELECT
        Id,
        Name,
        TerritoryName_Suggested__c,
        temp_AllocatorID__c,
        Need_Alignment__c,
        TerritoryMarket__c,
        TerritoryTeam__c,
        TerritorySegment__c,
        FreezeAlignment__c
      FROM Account
    ];

    //iterate through the accounts and Assert TerritoryName suggested__c field.
    //Pass accoutn as assert 3-rd parameter to see the value in case of failure
    for (Account acc : accs) {
      if (acc.Name == 'TestAccM') {
        system.assertEquals(
          acc.TerritoryName_Suggested__c == 'NORAM HIED Great Lakes',
          true,
          acc
        );
        system.assertEquals(acc.Need_Alignment__c, true, acc);
      } else if (acc.Name == 'TestAccNM') {
        system.assertEquals(
          acc.TerritoryName_Suggested__c == 'MISSED',
          true,
          acc
        );
      } else if (acc.Name == 'TestAccF') {
        system.assertEquals(acc.FreezeAlignment__c, true, acc);
        system.assertEquals(
          acc.TerritoryTeam__c == 'NORAM K12 East',
          true,
          acc
        );
        system.assertEquals(acc.TerritoryMarket__c == 'EDU', true, acc);
        system.assertEquals(acc.TerritorySegment__c == 'K12', true, acc);
      }
    }
  }

  /********************************************
test platform event trigger to generate error
in the START method of the BATCH
********************************************/
  @isTest
  static void testBatchApexErrorEvent() {
    Batch_Job_Monitor__c headeru = new Batch_Job_Monitor__c();
    headeru.BatchClassName__c = 'batchProcessAccountTerritory';
    headeru.Active__c = true;
    headeru.Log_Level__c = 'High';
    insert headeru;
    system.assertNotEquals(null, headeru.id, 'Header should exist in database');

    batchProcessAccountTerritory batchu;
    ID batchAsynchID;
    try {
      Test.startTest();
      batchu = new batchProcessAccountTerritory(null, null, -1);
      batchAsynchID = DataBase.executeBatch(batchu);
      Test.stopTest();
    } catch (Exception myEx) {
      System.Assert(
        true,
        'We do not care about the detail here. we assert at the bottom'
      );
    }
    Test.getEventBus().deliver();

    List<Batch_Job_Monitor_Item__c> bjmis = [
      SELECT id, Message__c, Parent_Job_Monitor__c
      FROM Batch_Job_Monitor_Item__c
    ];
    System.assertEquals(
      1,
      bjmis.size(),
      'Expect 1 Batch Job momitor Item due to exception'
    );
  }
}