force-app/main/default/objects/Account/fields/Name4Terr__c.field-meta.xml
<CustomField>
    <fullName>Name4Terr__c</fullName>
    <description>First char of the Name. Needed for TerrName calculation</description>
    <label>Name4Terr</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Need_Alignment__c.field-meta.xml
<CustomField>
    <fullName>Need_Alignment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need Alignment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ShippingPostalCode4Terr__c.field-meta.xml
<CustomField>
    <fullName>ShippingPostalCode4Terr__c</fullName>
    <description>needed by the TerritoryName calculation to store fraction of Zip code</description>
    <label>ShippingPostalCode4Terr</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TerritoryName_Suggested__c.field-meta.xml
<CustomField>
    <fullName>TerritoryName_Suggested__c</fullName>
    <description>Suggeste territory name</description>
    <label>TerritoryName Suggested</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FIND SUGGESTION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/Batch_Job_Monitor__c.object-meta.xml
<CustomObject>
    <description>object use tomtrack  batch class statistic</description>
    <label>Batch Job Monitor</label>
    <nameField>
        <displayFormat>BJM-{YYMMDD}-{000}</displayFormat>
        <label>Batch Job Monitor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BatchJobMonitors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>if active create child monitor records</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/BatchClassName__c.field-meta.xml
<CustomField>
    <fullName>BatchClassName__c</fullName>
    <label>BatchClassName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/BatchJobID__c.field-meta.xml
<CustomField>
    <fullName>BatchJobID__c</fullName>
    <externalId>true</externalId>
    <label>BatchJobID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/comment__c.field-meta.xml
<CustomField>
    <fullName>comment__c</fullName>
    <label>comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/Log_Level__c.field-meta.xml
<CustomField>
    <fullName>Log_Level__c</fullName>
    <label>Log Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/NrofFailures__c.field-meta.xml
<CustomField>
    <fullName>NrofFailures__c</fullName>
    <label>NrofFailures</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/nrofSuccess__c.field-meta.xml
<CustomField>
    <fullName>nrofSuccess__c</fullName>
    <label>nrofSuccess</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/fields/Parent_BatchMonitor__c.field-meta.xml
<CustomField>
    <fullName>Parent_BatchMonitor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent BatchMonitor</label>
    <referenceTo>Batch_Job_Monitor__c</referenceTo>
    <relationshipLabel>BatchJobMonitors</relationshipLabel>
    <relationshipName>BatchJobMonitors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor__c/recordTypes/Worker.recordType-meta.xml
<RecordType>
    <fullName>Worker</fullName>
    <active>true</active>
    <label>Worker</label>
</RecordType>

force-app/main/default/objects/Batch_Job_Monitor_Item__c/Batch_Job_Monitor_Item__c.object-meta.xml
<CustomObject>
    <label>Batch Job Monitor Item</label>
    <nameField>
        <displayFormat>BJMI-{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>Batch Job Monitor Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BatchJobMonitorItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Job_Monitor_Item__c/fields/Affected_record__c.field-meta.xml
<CustomField>
    <fullName>Affected_record__c</fullName>
    <label>Affected record</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor_Item__c/fields/Error_Phase__c.field-meta.xml
<CustomField>
    <fullName>Error_Phase__c</fullName>
    <label>Error Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>START</fullName>
            </value>
            <value>
                <fullName>EXECUTE</fullName>
            </value>
            <value>
                <fullName>FINISH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch_Job_Monitor_Item__c/fields/Parent_Job_Monitor__c.field-meta.xml
<CustomField>
    <fullName>Parent_Job_Monitor__c</fullName>
    <label>Parent Job Monitor</label>
    <referenceTo>Batch_Job_Monitor__c</referenceTo>
    <relationshipLabel>BatchJobMonitorItems</relationshipLabel>
    <relationshipName>BatchJobMonitorItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/batchProcessAccountAlocator.cls
/**********************************************************************************************************************************************************
Class Allocate  Account by callign a SOAP API Update call. also contaisn the Allocation Check and theOpp sync method
2020.04.29. try  to add statistic  info for the Opportunuty sync porcrss and store somehow in the BJM. (as comments) 
**********************************************************************************************************************************************************/
global class batchProcessAccountAlocator implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts, Database.RaisesPlatformEvents {
  Id account2Align;

  global integer totalSucess = 0;
  global integer totalFailure = 0;

  public integer nrofAccount;

  /************** used only during tests  ***********/
  public batchProcessAccountAlocator(integer thelimit) {
    nrofAccount = thelimit;
  }

/*****************************************
used for 1 Account alignment and TestClass
*****************************************/
  public batchProcessAccountAlocator(ID aID) {
    Account2Align = aID;
  }

  global Database.QueryLocator start(Database.BatchableContext theBC) {
    //AccountTerritoryNameBuilder.
    CreateBatchMonitor(
      theBC.getJobId(),
      'batchProcessAccountAlocator',
      0,
      0,
      'Alignment'
    );

    String query;
    query = 'Select ID, Name,Name4Terr__c, TerritoryName__c,TerritoryName_Suggested__c,ShippingPostalCode ,ShippingPostalCode4Terr__c';
    query = query + ' from Account where Need_Alignment__c = true ';

    if (Account2Align != null) {
      query = query + ' AND ID = \'' + Account2Align + '\'';
    }

    if (nrofAccount == null) {
      query = query + ' limit 500000';
    } else {
      query = query + 'limit ' + nrofAccount;
    }

    return Database.getQueryLocator(query);
  }

  /*********************************************************************
   collect all AccountId  and call SOAP API. Check the alocation results.
*********************************************************************/
  global void execute(Database.BatchableContext theBC, List<sObject> scope) {
    Set<Id> sA2A = new Set<ID>();

    for (Account theA : (List<Account>) scope) {
      sA2A.add(theA.id);
    }

    //we might have Exception in the Soap call caused by an Account, but other accounts might 
    //have been successfully aligned. In this case we shoud still do the checkAlignmentProcess
    try 
      {
      List<partnerSoapSforceCom.SaveResult> sr = AccountTerrAlocatorQueueable.AllignAccountSoap(sA2A);      
      } 
    catch (Exception myex) 
      {
      System.Debug('Exception occured during alignment call: ' + myex.getMessage()); //ES-36003
      }

    AlocationResult alocRes = AccountTerrAlocatorQueueable.checkAlignmentProcess(sA2A);
    totalSucess = totalSucess + alocRes.Success;
    totalFailure = totalFailure + alocRes.Failure;
    //2020.04.29. from the below we can see if the succesfully aligned Accounts were updated properly 
    //when clear the NeedAlignment flag AND we can see if the Opp2be synched were updated succesfully 
    //the opp. -sync monitor would be usefull to see how many Opps. were synched during the alignment.
    List<Database.SaveResult> dbSres = alocRes.dsrs;
  }

  global void finish(Database.BatchableContext theBC) {
    //AccountTerritoryNameBuilder.
    CreateBatchMonitor(
      theBC.getJobId(),
      'batchProcessAccountAlocator',
      totalSucess,
      totalFailure,
      'Alignment'
    );
  }

  /************************ the below 2 methods are helper methods for batch monitoring useb by both batc classes *******************************/

  /***********************************************************************************************************************************************
  In case we have an active Parent BJM for this class create a worker BJM.
  ***********************************************************************************************************************************************/
  public static Batch_Job_Monitor__c createBatchMonitor(
    Id batchJobID,
    String batchClassName,
    Integer success,
    Integer failure,
    String theComment
  ) {
    List<Batch_Job_Monitor__c> parentBJMs = [
      SELECT Id, Log_Level__c
      FROM Batch_Job_Monitor__c
      WHERE
        BatchClassName__c = :BatchClassName
        AND Parent_BatchMonitor__c = null
        AND Active__c = true
      LIMIT 1
    ];

    if (parentBJMs.size() == 0) {
      return null;
    }

    Batch_Job_Monitor__c thenewBJM = new Batch_Job_Monitor__c(
      Parent_BatchMonitor__c = parentBJMs[0].id,
      BatchClassName__c = batchClassName
    );
    thenewBJM.comment__c = theComment;
    thenewBJM.BatchJobID__c = batchJobID;
    thenewBJM.nrofSuccess__c = success;
    thenewBJM.NrofFailures__c = failure;
    //insert thenewBJM;
    Database.upsertresult durs = Database.upsert(
      thenewBJM,
      Batch_Job_Monitor__c.BatchJobID__c,
      false
    );
    thenewBJM.comment__c = parentBJMs[0].Log_Level__c; //just to pass the loglevel back to caller
    return thenewBJM;
  }

  /********************************************************************************************************************
  will bwe called from BatchApexErrorEvents_Trigger
  ********************************************************************************************************************/
  public static Batch_Job_Monitor_Item__c createBatchMonitorItem(
    ID bjmID,
    String themsg,
    String thePhase,
    String item
  ) {
    Batch_Job_Monitor_Item__c bjmi = new Batch_Job_Monitor_Item__c();
    bjmi.Parent_Job_Monitor__c = bjmID;
    bjmi.Message__c = themsg;
    bjmi.Error_Phase__c = thePhase;
    bjmi.Affected_record__c = item;

    return bjmi;
  }

  public class AlocationResult {
    public integer success;
    public integer failure;
    //2020.04.29. try  to extedn the class
    //in order to store DataBase operation
    public List<Database.SaveResult> dsrs;

    public AlocationResult() {
      success = 0;
      failure = 0;
    }

    public AlocationResult(integer s, integer f) {
      success = s;
      failure = f;
    }

    /************************* 2020.04.29. ************************/
    public void setDbSaveResult(List<Database.SaveResult> dsrs2pass)
    {
      dsrs = new List<Database.SaveResult>();
      dsrs.addAll(dsrs2pass);
    }
  }
}